version: 2
jobs:
  build:
    working_directory: ~/
    docker:
    - image: circleci/python:3.6.4
    steps:
      -checkout
      -run: sudo pip install pipenv
      -run: pipenv install sha3
      -run: pipenv run python test.py test
